### PR TITLE
Feature/decorators

### PR DESCRIPTION
**Pull request by callowaylc**

### CODE REVIEW

**Comment by callowaylc** [comment]
https://bloglovin.atlassian.net/browse/IO-957

```
christian@mon1:~$ cat /tmp/salt_metrics.json | json_pp
{
   "is_running" : 0,
   "saved_time" : "20151103212553",
   "minions" : {
      "rejected" : 0,
      "connected" : 3,
      "accepted" : 3,
      "pending" : 0,
      "denied" : 0
   },
   "id" : "",
   "func" : {},
   "role" : "master",
   "event" : {}
}
christian@mon1:~$ cat /tmp/salt_metrics.prometheus
salt_minions_accepted{is_running="0",role="master",saved_time="20151103212553",id=""} 3
salt_minions_connected{is_running="0",role="master",saved_time="20151103212553",id=""} 3
salt_minions_pending{is_running="0",role="master",saved_time="20151103212553",id=""} 0
salt_minions_rejected{is_running="0",role="master",saved_time="20151103212553",id=""} 0
salt_minions_denied{is_running="0",role="master",saved_time="20151103212553",id=""} 0
```

**Comment by hannahmimi** [comment]
LGTM

**Comment by jacksoncage** [comment]
@callowaylc the `HELP` and `TYPE` are needed on the prometheus response as well, I'm not seeing it in the example response, or is that only an example?

So the file need to be formatted exactly as example - https://github.com/bloglovin/salt-metrics/blob/feature/decorators/examples/prometheus-exposition

**Comment by jacksoncage** [comment]
To clarify 

```
salt_minions_accepted{is_running="0",role="master",saved_time="20151103212553",id=""} 3
```

should look like

```
salt_minions_accepted{role="master",id="mon1_master"} 73
```

**Comment by jacksoncage** [comment]
Let's exclude `saved_time` as a label.

**Comment by callowaylc** [comment]
```
christian@salt-dev:/tmp/salt-metrics$ sudo pip install -e /tmp/salt-metrics/
Obtaining file:///tmp/salt-metrics
  Running setup.py (path:/tmp/salt-metrics/setup.py) egg_info for package from file:///tmp/salt-metrics

Requirement already satisfied (use --upgrade to upgrade): salt>=2015.5.0 in /usr/lib/python2.7/dist-packages (from salt-metrics==0.0.4)
Installing collected packages: salt-metrics
  Running setup.py develop for salt-metrics

    Creating /usr/local/lib/python2.7/dist-packages/salt-metrics.egg-link (link to .)
    Adding salt-metrics 0.0.4 to easy-install.pth file

    Installed /tmp/salt-metrics
Successfully installed salt-metrics
Cleaning up...
```

**Comment by callowaylc** [comment]
image

**Comment by callowaylc** [comment]
```
christian@salt-dev:/tmp/salt-metrics$ cat /var/www/metrics/salt_metrics.prometheus
# HELP salt_event Number salt event by role
# TYPE salt_event gauge
salt_event_auth{is_running="1",role="master",id="master_master"} 368
salt_event_minion_job{is_running="1",role="master",id="master_master"} 9
salt_event_other{is_running="1",role="master",id="master_master"} 14610
salt_event_runner_ret{is_running="1",role="master",id="master_master"} 1
salt_event_minion_ret{is_running="1",role="master",id="master_master"} 79
salt_event_runner_job{is_running="1",role="master",id="master_master"} 1
# HELP salt_func Number salt func by role
# TYPE salt_func gauge
salt_func_runner.jobs.list_jobs{is_running="1",role="master",id="master_master"} 1
salt_func_saltutil.find_job{is_running="1",role="master",id="master_master"} 7
salt_func_cmd.run{is_running="1",role="master",id="master_master"} 2
# HELP salt_minions Number salt minions by role
# TYPE salt_minions gauge
salt_minions_accepted{is_running="1",role="master",id="master_master"} 16
salt_minions_connected{is_running="1",role="master",id="master_master"} 16
salt_minions_pending{is_running="1",role="master",id="master_master"} 0
salt_minions_rejected{is_running="1",role="master",id="master_master"} 0
salt_minions_denied{is_running="1",role="master",id="master_master"} 0
```

**Comment by jacksoncage** [comment]
Looking good @callowaylc !

LGTM!

**Pull request merged**
